### ISSUE TITLE
Front camera to dark

### ISSUE THREAD

**Issue by urosmil** [yuriy-budiyev/code-scanner#18] opened 2018-06-08 14:14 UTC
Hi, we have implemented your library without any trouble, but we are facing one issue. Front camera is too dark and can't read codes. We have tested camera by opening default device camera application and ti is much brighter and more clear than the screen we are getting through library in our app. Can you help us in resolving this? Thanks.

**Comment by yuriy-budiyev** [comment] 2018-06-13 13:43
I have some ideas about this, it should be fixed in next release. But I can't reproduce it on any of my test devices. This is probebly related to second issue of https://github.com/yuriy-budiyev/code-scanner/issues/19

**Comment by yuriy-budiyev** [comment] 2018-06-28 10:37
Hi, in 1.9.1 scanner will keep default frame rate range if min >= 10 and max <= 30. Please tell if it fixes the problem. Also, in 1.9.1 fixed some exposure bugs, probably it will help too.

**Closed** 2018-07-23 14:53 UTC
